version: '3'
services:
  tg_bot:
    image: "bot"
    container_name: telegram-bot-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - '.env'
    depends_on:
      - postgres
      - redis
    networks:
      - bot-network

  redis:
    image: redis:latest
    container_name: redis-container
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - '.env'
    ports:
      - "6379:6379"
    networks:
      - bot-network

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres-container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
          - "5439:5432"
    networks:
      - bot-network

networks:
  bot-network:
