"""Autogenerated migration

Revision ID: 10cfcda2df2f
Revises: 05be8b24f0ec
Create Date: 2024-05-31 09:02:32.116402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10cfcda2df2f'
down_revision: Union[str, None] = '05be8b24f0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
