"""Autogenerated migration

Revision ID: 52f35b6f937b
Revises: acc8f3d8ab2c
Create Date: 2024-05-31 08:58:57.387520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f35b6f937b'
down_revision: Union[str, None] = 'acc8f3d8ab2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
