"""Autogenerated migration

Revision ID: 82c5c2286eae
Revises: f53d7c9b7dac
Create Date: 2024-05-31 08:55:53.483145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c5c2286eae'
down_revision: Union[str, None] = 'f53d7c9b7dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
