"""Autogenerated migration

Revision ID: acc8f3d8ab2c
Revises: 38e7c30df70c
Create Date: 2024-05-31 08:58:19.801200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc8f3d8ab2c'
down_revision: Union[str, None] = '38e7c30df70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
